language: c
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

install:
  - bash -x devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true
  - export PATH=$HOME/miniconda3/bin:$PATH

script:

  # Create an environment for testing
  - conda create --yes -n test python=$python
  - source activate test
  # Add omnia channel for packages
  - conda config --add channels omnia
  # Add conda-force channel for packages
  - conda config --add channels conda-forge

  # Install package dependencies
  - conda install --yes --file devtools/travis-ci/requirements.txt
  - python setup.py install

  # Test the package
  - nosetests -v

env:
  matrix:
    - python=2.7  CONDA_PY=27
    - python=3.5  CONDA_PY=35
    - python=3.6  CONDA_PY=36

after_success:
  - bash -x devtools/travis-ci/after_success.sh
